name: vizemo

channels:
- conda-forge

dependencies:
  - python=3.6.7
  - ipykernel=5.1.0
  - ipython=7.4.0
  - ipython-genutils=0.2.0
  - ipywidgets=7.4.2
  - jupyter=1.0.0
  - jupyter-client=5.2.4
  - jupyter-console=6.0.0
  - jupyter-core=4.4.0
  - matplotlib=3.0.3
  - notebook=5.7.6
  - numpy=1.16.2
  - pandas=0.24.2
  - pyhull=2015.2.1
  - scikit-learn=0.20.3
  - scipy=1.2.1
  - seaborn=0.9.0
  - sklearn=0.0
